AllCops:
  TargetRubyVersion: 2.3

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/AlignParameters:
  Exclude:
    - 'Gemfile'
  EnforcedStyle: with_fixed_indentation

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/ModuleFunction:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
