require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/AlignParameters:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/ModuleFunction:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountComments: false

Metrics/LineLength:
  AllowURI: true
  Max: 85

Metrics/MethodLength:
  CountComments: false

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 1559
