version: '2'

services:
  common: &BASE
    build:
      context: .
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    environment:
      - JRUBY_OPTS=--dev
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mri: &MRI
    <<: *BASE
    build:
      context: .
      dockerfile: Dockerfile-mri
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}

  tests:
    <<: *BASE
    command: bin/rspec

  tests-mri:
    <<: *MRI
    command: bin/rspec

  dev:
    <<: *BASE
    ports:
      - '9292:9292'
    command: bin/puma -b tcp://0.0.0.0:9292 config.ru

  dev-mri:
    <<: *MRI
    ports:
      - '9292:9292'
    command: bin/puma -b tcp://0.0.0.0:9292 config.ru
