version: '2'

services:
  jruby:
    build:
      context: .
      dockerfile: Dockerfile-jruby
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    environment:
      - JRUBY_OPTS=--dev
    dns:
      - 8.8.8.8
      - 8.8.4.4

  mri:
    build:
      context: .
      dockerfile: Dockerfile-mri
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    dns:
      - 8.8.8.8
      - 8.8.4.4

  tests-jruby:
    extends: jruby
    command: bin/rspec

  tests-mri:
    extends: mri
    command: bin/rspec

  dev-jruby:
    extends: jruby
    ports:
      - '9292:9292'
    command: bin/puma -b tcp://0.0.0.0:9292 config.ru

  dev-mri:
    extends: mri
    ports:
      - '9292:9292'
    command: bin/puma -b tcp://0.0.0.0:9292 config.ru

  console-jruby:
    extends: jruby
    command: bin/console

  console-mri:
    extends: mri
    command: bin/console
